### ISSUE TITLE
similar Widget needed

### ISSUE THREAD

**Issue by makomba** [wolfoerster/EquationOfTime#1]
Hello wolfoerster, I found here in your account this EquationOfTime project and would like to ask you something.

With the equation of time I have programmed a website with Javascript, but what I am looking for is a widget for mobile devices (Android, Apple, ...).

I have been informed, but it is too much effort for the small thing. I think that it is not very much effort for someone who can already program apps. That's why I wanted to ask you.

The widget should be able to be placed on the desktop screen like other clocks so that it is always visible. The following should be displayed:

(Digits) Normal time HH: MM: SS
(Digits) Sundial Time HH: MM: SS

Sundial Time = Normal Time + - eqt + - longitude.

There is a formula for calculating the eqt. The sundial should also be calculated by UTC and by longitude. For the calculation with the longitude it needs a query of the GPS data.

I would love if the widget is otherwise clean in terms of privacy and ads.

Furthermore, I have a very similar second idea, which requires only a formula and no GPS.

If that is feasible for you, I would be happy.

**Comment by wolfoerster** [comment]
Hi makomba,
Thanks for your interesting idea!
Unfortunately I am not able to write apps for mobile devices.
Wishing you good luck - there are surely lots of people out in the world who can help you.
